[tool.poetry]
name = "queueforge"
version = "0.1.0"
description = ""
authors = ["Ankit Shrestha <ankit.shrestha196@gmail.com>"]
readme = "README.md"
packages = [{ include = "queueforge", from = "src" }]

[tool.poetry.dependencies]
python = "^3.14"
fastapi = "^0.136.3"
uvicorn = "^0.48.0"
fire = "^0.7.1"
loguru = "^0.7.3"
ariadne = "^1.0.1"
shortuuid = "^1.0.13"
opentelemetry-api = "^1.42.1"
pydantic-settings = "^2.14.1"
pyyaml = "^6.0.3"
sqlalchemy = "^2.0.50"
psycopg = { extras = ["binary"], version = "^3.3.4" }
dependency-injector = "^4.49.1"
alembic = "^1.19.0"

[tool.poetry.scripts]
cli = "cli.cli:main"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
